import fs from "fs";
import path from "path";
import { Plugin } from "vite";

function generateCssVariablesPlugin({
  assetsDir = "./src/assets",
  outputFile = "./src/assets/variables.css",
}: {
  assetsDir?: string;
  outputFile?: string;
}): Plugin {
  const supportedExtensions = [
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".mp4",
    ".webm",
    ".avi",
  ];

  const baseNameMap = new Map<string, string[]>(); // Map base names to file paths

  function generateCssVariables(dir: string, prefix = "--", mode: string) {
    const files = fs.readdirSync(dir, { withFileTypes: true });
    let cssVariables = "";

    files.forEach((file) => {
      const fullPath = path.join(dir, file.name);

      if (file.isDirectory()) {
        cssVariables += generateCssVariables(fullPath, prefix, mode);
      } else {
        const ext = path.extname(file.name).toLowerCase();
        if (supportedExtensions.includes(ext)) {
          const baseName = path
            .basename(file.name, ext)
            .replace(/\s+/g, "-")
            .toLowerCase();

          // Track file paths for each base name
          if (!baseNameMap.has(baseName)) {
            baseNameMap.set(baseName, []);
          }
          baseNameMap.get(baseName)!.push(fullPath);

          let relativePath = fullPath.replace(
            path.resolve("./src"),
            mode === "development" ? "./src" : ""
          ); // Adjust relative path
          relativePath = relativePath.replace(/\\/g, "/"); // Replace backslashes with forward slashes for CSS compatibility
          cssVariables += `${prefix}${baseName}: url('${relativePath}');\n`;
        }
      }
    });

    return cssVariables;
  }

  function writeCssVariables(mode: string) {
    try {
      baseNameMap.clear(); // Clear the map before generating variables
      const cssContent = `/* WARNING: This file is autogenerated. Do not edit directly. */\n\n:root {\n${generateCssVariables(
        path.resolve(assetsDir),
        "  --",
        mode
      )}}`;
      fs.mkdirSync(path.dirname(outputFile), { recursive: true }); // Ensure directory exists
      fs.writeFileSync(outputFile, cssContent, "utf8");

      // Check for duplicates
      const duplicates = Array.from(baseNameMap.entries()).filter(
        ([, paths]) => paths.length > 1
      );

      if (duplicates.length > 0) {
        const duplicateMessage = duplicates
          .map(
            ([baseName, paths]) =>
              `Duplicate base name "${baseName}" found in:\n` +
              paths.map((p) => `- ${p}`).join("\n")
          )
          .join("\n\n");

        throw new Error(
          `❌ Duplicate base names detected:\n\n${duplicateMessage}\n\nPlease ensure all file base names are unique.`
        );
      }

      console.log(`✅ CSS variables generated: ${outputFile}`);
    } catch (error: any) {
      console.error(`❌ Error generating CSS variables: ${error.message}`);
      process.exit(1); // Stop the build process
    }
  }

  return {
    name: "vite-plugin-generate-css-variables",
    apply: process.env.NODE_ENV === "development" ? "serve" : "build", // Run during development and builds
    enforce: "pre", // Enforce the plugin to run before other plugins
    configResolved({ mode }) {
      // Generate CSS variables when the config is resolved
      writeCssVariables(mode);
    },
    configureServer(server) {
      const fullAssetsDir = path.resolve(assetsDir);

      server.watcher.add(fullAssetsDir); // Watch the directory
      server.watcher.on("add", (filePath) => {
        if (filePath.startsWith(fullAssetsDir)) {
          console.log(`📄 File added: ${filePath}`);
          writeCssVariables("development");
        }
      });

      server.watcher.on("change", (filePath) => {
        if (filePath.startsWith(fullAssetsDir)) {
          console.log(`✏️ File changed: ${filePath}`);
          writeCssVariables("development");
        }
      });

      server.watcher.on("unlink", (filePath) => {
        if (filePath.startsWith(fullAssetsDir)) {
          console.log(`🗑️ File deleted: ${filePath}`);
          writeCssVariables("development");
        }
      });
    },
  };
}

export default generateCssVariablesPlugin;
